/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Cars;
import Model.CarsHistory;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author rohinibalasubramanian
 */

public class CreateJPanel extends javax.swing.JPanel {
    /**
     * Creates new form CreateJPanel
     
     */
    CarsHistory history;
    
    public CreateJPanel(CarsHistory history) {
        
        initComponents();  
        
        this.history = history;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCarCompany = new javax.swing.JLabel();
        lblManufactureYear = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        ComboxCity = new javax.swing.JComboBox<>();
        lblAvailability = new javax.swing.JLabel();
        YesCheckBox1 = new javax.swing.JCheckBox();
        noCheckBox2 = new javax.swing.JCheckBox();
        lblType = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        comboCar = new javax.swing.JComboBox<>();
        comboyear = new javax.swing.JComboBox<>();
        lblMain = new javax.swing.JLabel();
        ComboAct = new javax.swing.JComboBox<>();
        lbltext = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        lblTitle.setText("CreatePanel");

        lblCarCompany.setText("CarCompany");

        lblManufactureYear.setText("Manufacture Year");

        lblSerialNumber.setText("Model Number");

        lblCity.setText("City");

        txtSerialNumber.setToolTipText("CJ329ZTUTTBT6WDI3");
        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });
        txtSerialNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerialNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerialNumberKeyReleased(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 204, 204));
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        ComboxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Francisco", "Boston", "New York ", "Dallas" }));
        ComboxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxCityActionPerformed(evt);
            }
        });

        lblAvailability.setText("Availability");

        YesCheckBox1.setText("Yes");
        YesCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesCheckBox1ActionPerformed(evt);
            }
        });

        noCheckBox2.setText("No");

        lblType.setText("Uber Type ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uber X ", "Uber XL", "Uber Pool", "Uber SUV ", "Uber Select ", "Uber ExpressPool", "Uber Lux ", "Uber Wave" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("No.of seats");

        jSlider1.setBackground(new java.awt.Color(255, 204, 204));
        jSlider1.setMajorTickSpacing(2);
        jSlider1.setMaximum(6);
        jSlider1.setMinimum(2);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        comboCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota ", "GM ", "Mazda", "Honda", "Dodge" }));

        comboyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        lblMain.setText("Maintenance Certificate");

        ComboAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active ", "Inactive" }));
        ComboAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboActActionPerformed(evt);
            }
        });

        lbltext.setEditable(false);
        lbltext.setBackground(new java.awt.Color(204, 255, 255));
        lbltext.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMain)
                    .addComponent(lblCity)
                    .addComponent(jLabel1)
                    .addComponent(lblType)
                    .addComponent(lblAvailability)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblManufactureYear)
                            .addComponent(lblCarCompany)
                            .addComponent(lblSerialNumber))
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(comboCar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(YesCheckBox1)
                            .addGap(34, 34, 34)
                            .addComponent(noCheckBox2))
                        .addComponent(ComboxCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSerialNumber))
                    .addComponent(ComboAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarCompany)
                    .addComponent(comboCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufactureYear)
                    .addComponent(comboyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSerialNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(YesCheckBox1)
                    .addComponent(noCheckBox2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblType))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(ComboxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMain)
                    .addComponent(ComboAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ComboxCity, txtSerialNumber});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "New Information added");
        String CarCompany = comboCar.getSelectedItem().toString();
        String year = comboyear.getSelectedItem().toString();
        int SerialNumber = Integer.parseInt(txtSerialNumber.getText());
        
        String City = ComboxCity.getSelectedItem().toString();
        String uber = jComboBox1.getSelectedItem().toString();
        String seating = Integer.toString(jSlider1.getValue());
        String main = ComboAct.getSelectedItem().toString();
       // String seating = newcb.getSelectedItem().toString();
       
        
        String availability = null;
        
        if(YesCheckBox1.isSelected())
        {
            availability = "yes";
        }else if(noCheckBox2.isSelected())
        {
           availability = "no"; 
        }else
        {
            availability = "no"; 
        }
            
            
        //String City = txtCity.getText();
        
        
        Cars c = history.addNewCars();
        
        
        
        c.setCarcompany(CarCompany);
        c.setYear(year);
                                           
        // TODO add your handling code here:
        String PATTERN = "(?=.*\\d|=.*[A-Z])(?=.*[A-Z])[A-Z0-9]{17}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(txtSerialNumber.getText());
        if(!match.matches()){
            lbltext.setText("Invalid Model Number ");
            
            
        }
        
        else{
            lbltext.setText(null);
            c.setSerial_no(SerialNumber);
            //int SerialNumber = Integer.parseInt(txtSerialNumber.getText());
            
                    }
        
        c.setAvailability(availability);
        c.setCity(City);
        //c.setCity(City);
        c.setUbertype(uber);
        c.setSeats(seating);
        c.setMaintenance(main);
        
        
        JOptionPane.showMessageDialog(this, "New Information added");
        
        /* txtPassengerCar.setText("");
        txtModelNumber.setText("");
        txtSerialNumber.setText("");
        */
       
             
    }//GEN-LAST:event_btnSaveActionPerformed

    private void ComboxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxCityActionPerformed
        // TODO add your handling code here:
        // define items in a vector collection:
        


    }//GEN-LAST:event_ComboxCityActionPerformed

    private void YesCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesCheckBox1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jSlider1StateChanged

    private void ComboActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboActActionPerformed

    private void txtSerialNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumberKeyReleased
        // TODO add your handling code here:
        {                                    
        // TODO add your handling code here:
        String PATTERN = "(?=.*\\d|=.*[A-Z])(?=.*[A-Z])[A-Z0-9]{17}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(txtSerialNumber.getText());
        if(!match.matches()){
            lbltext.setText("Invalid Serial Number ");
            
            
        }
        
        else{
            lbltext.setText(null);
            int SerialNumber = Integer.parseInt(txtSerialNumber.getText());
            
        }
    }                                   
        
    }//GEN-LAST:event_txtSerialNumberKeyReleased

    private void txtSerialNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNumberKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtSerialNumberKeyPressed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAct;
    private javax.swing.JComboBox<String> ComboxCity;
    private javax.swing.JCheckBox YesCheckBox1;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboCar;
    private javax.swing.JComboBox<String> comboyear;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCarCompany;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField lbltext;
    private javax.swing.JCheckBox noCheckBox2;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
