/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Cars;
import Model.CarsHistory;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowFilter.ComparisonType;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rohinibalasubramanian
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     * 
     */
    DefaultTableModel model ;
     CarsHistory history;
    public ViewJPanel(CarsHistory history) {
        initComponents();
        this.history = history;
        
        populateTable();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtSerialNumber = new javax.swing.JTextField();
        lblCarCompany = new javax.swing.JLabel();
        lblManufactureYear = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        ComboxCity = new javax.swing.JComboBox<>();
        lblAvailability = new javax.swing.JLabel();
        YesCheckBox1 = new javax.swing.JCheckBox();
        noCheckBox2 = new javax.swing.JCheckBox();
        lblType = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();
        comboCar = new javax.swing.JComboBox<>();
        comboyear = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        txtupdate = new javax.swing.JTextField();
        lblMain = new javax.swing.JLabel();
        ComboAct = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        brandcmbbx = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        comboyearr = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        cmbxloc = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        cmbxtype = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        cmbxAct = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        ComboxCity1 = new javax.swing.JComboBox<>();
        YesCheckBox2 = new javax.swing.JCheckBox();
        noCheckBox3 = new javax.swing.JCheckBox();
        btnminmax = new javax.swing.JButton();
        newcb = new javax.swing.JComboBox<>();
        newcb1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 204, 153));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        lblTitle.setText("     View Panel");

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Company", "Manufacture Year", "City", "Availability", "Model Number", "UberType", "Seats", "Maintenance Certificate", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblView);

        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 204, 204));
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 153), null, null));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtSerialNumber.setBackground(new java.awt.Color(204, 255, 204));
        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        lblCarCompany.setText("CarCompany");

        lblManufactureYear.setText("Manufacture Year");

        lblSerialNumber.setText("Model Number");

        lblCity.setText("City");

        txtSearch.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtSearch.setToolTipText("Search for the item");
        txtSearch.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));
        txtSearch.setCaretColor(new java.awt.Color(153, 153, 153));
        txtSearch.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        ComboxCity.setBackground(new java.awt.Color(204, 255, 204));
        ComboxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Francisco", "Boston", "New York ", "Dallas" }));
        ComboxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxCityActionPerformed(evt);
            }
        });

        lblAvailability.setText("Availability");

        YesCheckBox1.setText("Yes");
        YesCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesCheckBox1ActionPerformed(evt);
            }
        });

        noCheckBox2.setText("No");

        lblType.setText("Uber Type ");

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uber X ", "Uber XL", "Uber Pool", "Uber SUV ", "Uber Select ", "Uber ExpressPool", "Uber Lux ", "Uber Wave" }));
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });

        comboCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota ", "GM ", "Mazda", "Honda", "Dodge" }));

        comboyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        jLabel1.setText("Seats");

        jSlider1.setBackground(new java.awt.Color(255, 204, 204));
        jSlider1.setMajorTickSpacing(2);
        jSlider1.setMaximum(6);
        jSlider1.setMinimum(2);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel2.setText("Fleet Catalog update time:");

        txtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupdateActionPerformed(evt);
            }
        });

        lblMain.setText("Maintenance Certificate");

        ComboAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active ", "Inactive" }));
        ComboAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboActActionPerformed(evt);
            }
        });

        jButton1.setText("List by Car Company");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        brandcmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota ", "GM ", "Mazda", "Honda", "Dodge" }));

        jButton2.setText("List by Year");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        comboyearr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        jButton3.setText("List by City ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cmbxloc.setBackground(new java.awt.Color(204, 255, 204));
        cmbxloc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Francisco", "Boston", "New York ", "Dallas" }));
        cmbxloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxlocActionPerformed(evt);
            }
        });

        jButton4.setText("List by UberType");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cmbxtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uber X ", "Uber XL", "Uber Pool", "Uber SUV ", "Uber Select ", "Uber ExpressPool", "Uber Lux ", "Uber Wave" }));
        cmbxtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxtypeActionPerformed(evt);
            }
        });

        jButton5.setText("List by Expiration ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cmbxAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active ", "Inactive" }));
        cmbxAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxActActionPerformed(evt);
            }
        });

        jButton6.setText("First available passenger Car ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        ComboxCity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Francisco", "Boston", "New York ", "Dallas" }));
        ComboxCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboxCity1ActionPerformed(evt);
            }
        });

        YesCheckBox2.setText("Yes");
        YesCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesCheckBox2ActionPerformed(evt);
            }
        });

        noCheckBox3.setText("No");

        btnminmax.setText("Select min & max seat ");
        btnminmax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminmaxActionPerformed(evt);
            }
        });

        newcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));

        newcb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YesCheckBox2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noCheckBox3))
                                    .addComponent(ComboxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManufactureYear)
                                    .addComponent(lblCarCompany)
                                    .addComponent(lblSerialNumber)
                                    .addComponent(lblCity)
                                    .addComponent(lblAvailability)
                                    .addComponent(lblType)
                                    .addComponent(jLabel1)
                                    .addComponent(lblMain))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboAct, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboxCity, 0, 145, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(YesCheckBox1)
                                        .addGap(105, 105, 105)
                                        .addComponent(noCheckBox2))
                                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboyear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboCar, 0, 247, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(txtupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnminmax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(newcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(brandcmbbx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboyearr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbxloc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbxtype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbxAct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ComboxCity, comboCar, comboType, comboyear});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {brandcmbbx, cmbxAct, cmbxloc, cmbxtype, comboyearr});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(8, 8, 8)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(brandcmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboyearr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbxloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(cmbxtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbxAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jButton5)
                                .addGap(11, 11, 11)
                                .addComponent(btnminmax))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboxCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YesCheckBox2)
                            .addComponent(noCheckBox3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarCompany)
                            .addComponent(comboCar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblManufactureYear))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSerialNumber)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(ComboxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvailability)
                            .addComponent(YesCheckBox1)
                            .addComponent(noCheckBox2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblType)
                            .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMain)
                                    .addComponent(ComboAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDelete, btnUpdate});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {brandcmbbx, cmbxAct, cmbxloc, cmbxtype, comboyearr});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblView.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            
        }
        
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        Cars selectedCars = (Cars) model.getValueAt(selectedRowIndex, 0);
        
        history.deleteCars(selectedCars);
        
        JOptionPane.showMessageDialog(this, "Car details deleted");
        
        populateTable();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
    //showDateTime();
    

        DefaultTableModel tblModel = (DefaultTableModel) tblView.getModel();
        if( tblView.getSelectedRowCount() == 1){
            
           // String PassengerCar = txtPassengerCar.getText();
            String CarCompany = comboCar.getSelectedItem().toString();
            String ManufactureYear = comboyear.getSelectedItem().toString();
            String Serial_no = txtSerialNumber.getText();
            String combo = ComboxCity.getSelectedItem().toString();
            String type = comboType.getSelectedItem().toString();
            String seating = Integer.toString(jSlider1.getValue());
            String main = ComboAct.getSelectedItem().toString();
            Date d = new Date();
            SimpleDateFormat sdt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            txtupdate.setText(sdt.format(d));
            String time = txtupdate.getText();
                    
                    
              String avail = null;
        if(YesCheckBox1.isSelected())
        {
            avail = "yes";
        }else if(noCheckBox2.isSelected())
        {
           avail = "no"; 
        }else
        {
            avail = "no"; 
        }
            
           
            
            //tblModel.setValueAt(PassengerCar, tblView.getSelectedRow(), 0);
            tblModel.setValueAt(CarCompany, tblView.getSelectedRow(), 0);
            tblModel.setValueAt(ManufactureYear, tblView.getSelectedRow(), 1);
            tblModel.setValueAt(Serial_no, tblView.getSelectedRow(), 4);
            tblModel.setValueAt(combo, tblView.getSelectedRow(), 2); 
            tblModel.setValueAt(avail, tblView.getSelectedRow(), 3);
            tblModel.setValueAt(type, tblView.getSelectedRow(), 5);
            tblModel.setValueAt(seating, tblView.getSelectedRow(), 6);
            tblModel.setValueAt(main, tblView.getSelectedRow(),7);
            tblModel.setValueAt(time, tblView.getSelectedRow(), 8);
            
            
      
            
            JOptionPane.showMessageDialog(this, "Updated Successfully!");
            JOptionPane.showMessageDialog(null,"Update time of the catalog noted");
            
        }else{
            if(tblView.getRowCount()==0) {
                JOptionPane.showMessageDialog(this, "Table is empty");
            }else {
                                JOptionPane.showMessageDialog(this, "Please select single row to update");

            }
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tblView.getModel();
        //String tblPassengercar = tblModel.getValueAt(tblView.getSelectedRow(), 0).toString();
        String tblCarcompany = tblModel.getValueAt(tblView.getSelectedRow(), 0).toString();
        String tblManufactureYear = tblModel.getValueAt(tblView.getSelectedRow(), 1).toString();
        String tblAvail= tblModel.getValueAt(tblView.getSelectedRow(), 3).toString();
        String city = tblModel.getValueAt(tblView.getSelectedRow(), 2).toString();
        String tblSerialNum= tblModel.getValueAt(tblView.getSelectedRow(), 4).toString();
        String tblUber = tblModel.getValueAt(tblView.getSelectedRow(), 5).toString();
        String tblSeat = tblModel.getValueAt(tblView.getSelectedRow(), 6).toString();
        String tblMain = tblModel.getValueAt(tblView.getSelectedRow(), 7).toString();
        
        
      


        
       
        
        //txtPassengerCar.setText(tblPassengercar);
        comboCar.setSelectedItem(tblCarcompany);
        comboyear.setSelectedItem(tblManufactureYear);
        if(tblAvail.equals(true)){
           YesCheckBox1.setSelected(true); 
        
        }
        else if (tblAvail.equals(false)){
        noCheckBox2.setSelected(true);
        }
        else{
            noCheckBox2.setSelected(true);
        }
        
        ComboxCity.setSelectedItem(city);
        txtSerialNumber.setText(tblSerialNum);
        comboType.setSelectedItem(tblUber);
        ComboAct.setSelectedItem(tblMain);
       // newcb2.setSelectedItem(tblSeat);
       
       
        
        
        
    }//GEN-LAST:event_tblViewMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
      DefaultTableModel model = (DefaultTableModel) tblView.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      tblView.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(txtSearch.getText().trim()));
              
    }//GEN-LAST:event_txtSearchKeyPressed

    private void ComboxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxCityActionPerformed
        // TODO add your handling code here:
        // define items in a vector collection:

    }//GEN-LAST:event_ComboxCityActionPerformed

    private void YesCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesCheckBox1ActionPerformed

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTypeActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jSlider1StateChanged

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void txtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtupdateActionPerformed

    private void ComboActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboActActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String brand = brandcmbbx.getSelectedItem().toString();
        searchbrand(brand);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String yearr = comboyearr.getSelectedItem().toString();
        searchyear(yearr);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbxlocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxlocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxlocActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String loc = cmbxloc.getSelectedItem().toString();
        searchloc(loc);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbxtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxtypeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String Utype = cmbxtype.getSelectedItem().toString();
        searchtype(Utype);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmbxActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxActActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String exp = cmbxAct.getSelectedItem().toString();
        searchexp(exp);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ComboxCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboxCity1ActionPerformed
        // TODO add your handling code here:
        // define items in a vector collection:

    }//GEN-LAST:event_ComboxCity1ActionPerformed

    private void YesCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesCheckBox2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String city = ComboxCity1.getSelectedItem().toString();
        String avail = null;
        if(YesCheckBox2.isSelected())
        {
            avail = "yes";
        }else if(noCheckBox3.isSelected())
        {
           avail = "no"; 
        }
        
        ArrayList<RowFilter<Object,Object>> filters = new ArrayList<RowFilter<Object,Object>>(2);
        filters.add(RowFilter.regexFilter(city));
        filters.add(RowFilter.regexFilter(avail));
        RowFilter<Object,Object> yesloc = RowFilter.andFilter(filters);
        model = (DefaultTableModel) tblView.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tblView.setRowSorter(trs);
        trs.setRowFilter(yesloc);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnminmaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminmaxActionPerformed
        // TODO add your handling code here:
//        int min = Integer.parseInt(newcb.getSelectedItem().toString());
//        int max = Integer.parseInt(newcb1.getSelectedItem().toString());
        String min = newcb.getSelectedItem().toString();
        String max = newcb1.getSelectedItem().toString();

        ArrayList<RowFilter<Object,Object>> filters = new ArrayList<RowFilter<Object,Object>>(2);

        filters.add(RowFilter.regexFilter(min));
        filters.add(RowFilter.regexFilter(max));
       
        RowFilter<Object,Object> minmax = RowFilter.andFilter(filters);

        model = (DefaultTableModel) tblView.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tblView.setRowSorter(trs);
        trs.setRowFilter(minmax);
    }//GEN-LAST:event_btnminmaxActionPerformed
public void searchbrand(String str)
{
      DefaultTableModel model = (DefaultTableModel) tblView.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      tblView.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(str));
}

public void searchyear(String str)
{
    DefaultTableModel model = (DefaultTableModel) tblView.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      tblView.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(str));
}

public void searchloc(String str)
{
    DefaultTableModel model = (DefaultTableModel) tblView.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      tblView.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(str));
    
}

public void searchtype(String str)
{
    DefaultTableModel model = (DefaultTableModel) tblView.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      tblView.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(str));
    
}
public void searchexp(String str)
{
    DefaultTableModel model = (DefaultTableModel) tblView.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      tblView.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(str));
    
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboAct;
    private javax.swing.JComboBox<String> ComboxCity;
    private javax.swing.JComboBox<String> ComboxCity1;
    private javax.swing.JCheckBox YesCheckBox1;
    private javax.swing.JCheckBox YesCheckBox2;
    private javax.swing.JComboBox<String> brandcmbbx;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnminmax;
    private javax.swing.JComboBox<String> cmbxAct;
    private javax.swing.JComboBox<String> cmbxloc;
    private javax.swing.JComboBox<String> cmbxtype;
    private javax.swing.JComboBox<String> comboCar;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JComboBox<String> comboyear;
    private javax.swing.JComboBox<String> comboyearr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblCarCompany;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JComboBox<String> newcb;
    private javax.swing.JComboBox<String> newcb1;
    private javax.swing.JCheckBox noCheckBox2;
    private javax.swing.JCheckBox noCheckBox3;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtupdate;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        
        DefaultTableModel model = (DefaultTableModel) tblView.getModel();
        model.setRowCount(0);
        
        for(Cars c : history.getHistory()){
            
            Object[] row = new Object[20];
            row[0]= c;
            row[1]= c.getYear();

            row[2]= c.getCity();
            row[3]= c.getAvailability();
            row[4]= c.getSerial_no();
            row[5]= c.getUbertype();
            row[6]= c.getSeats();
            row[7]= c.getMaintenance();
            
            
            model.addRow(row);
            
        }
        
        
        
           }
}
