/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Product;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author rohinibalasubramanian
 */
public class createJpanel extends javax.swing.JPanel {

    /**
     * Creates new form createJpanel
     */
    Product product;
    
    public createJpanel(Product product) {
        initComponents();
        this.product = product;
        createpanel.setVisible(false);
        createpanel1.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btnFax = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        createpanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnName1 = new javax.swing.JLabel();
        btnDOB1 = new javax.swing.JLabel();
        btnCountry1 = new javax.swing.JLabel();
        btnTelephone1 = new javax.swing.JLabel();
        btnEmail1 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txttelephone = new javax.swing.JTextField();
        txtcountry = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        lbltext = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtlinkedin1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblfax = new javax.swing.JLabel();
        txtfax = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCheckBox2 = new javax.swing.JCheckBox();
        createpanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblmedrec = new javax.swing.JLabel();
        lblhealthplan = new javax.swing.JLabel();
        lblbankacc = new javax.swing.JLabel();
        lbllicense = new javax.swing.JLabel();
        lblvehicle = new javax.swing.JLabel();
        lbldev = new javax.swing.JLabel();
        lblIntProt = new javax.swing.JLabel();
        txtinternetprotocol = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtmedrec = new javax.swing.JTextField();
        txthealthplan = new javax.swing.JTextField();
        txtbankacc = new javax.swing.JTextField();
        txtlicense = new javax.swing.JTextField();
        txtvehicle = new javax.swing.JTextField();
        txtdev = new javax.swing.JTextField();
        btnphoto = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(51, 153, 255));
        btnSave.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Personal Data");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        createpanel.setBackground(new java.awt.Color(255, 204, 204));

        lblTitle.setBackground(new java.awt.Color(255, 204, 204));
        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setText("Personal Data");

        btnName1.setText("Name:");

        btnDOB1.setText("DOB:");

        btnCountry1.setText("Country:");

        btnTelephone1.setText("Telephone:");

        btnEmail1.setText("Email:");

        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });

        txttelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelephoneActionPerformed(evt);
            }
        });
        txttelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttelephoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelephoneKeyTyped(evt);
            }
        });

        txtcountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcountryKeyReleased(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        lbltext.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbltext.setForeground(new java.awt.Color(255, 51, 51));

        jLabel6.setText("LinkedIn:");

        txtlinkedin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlinkedin1ActionPerformed(evt);
            }
        });
        txtlinkedin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlinkedin1KeyReleased(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));

        lblfax.setText("Fax");

        txtfax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfaxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout createpanelLayout = new javax.swing.GroupLayout(createpanel);
        createpanel.setLayout(createpanelLayout);
        createpanelLayout.setHorizontalGroup(
            createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createpanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createpanelLayout.createSequentialGroup()
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createpanelLayout.createSequentialGroup()
                        .addGap(15, 357, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createpanelLayout.createSequentialGroup()
                        .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createpanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEmail1)
                                    .addComponent(jLabel6)
                                    .addComponent(lblfax)))
                            .addGroup(createpanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125)
                        .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcountry, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(txttelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(txtlinkedin1)
                            .addComponent(txtfax)
                            .addComponent(txtname)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createpanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createpanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblTitle))
                            .addGroup(createpanelLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnName1)
                            .addGroup(createpanelLayout.createSequentialGroup()
                                .addComponent(btnDOB1)
                                .addGap(147, 147, 147)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTelephone1)))
                .addContainerGap())
        );
        createpanelLayout.setVerticalGroup(
            createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createpanelLayout.createSequentialGroup()
                        .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnName1)
                            .addComponent(txtname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnDOB1))
                    .addGroup(createpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCountry1)
                    .addComponent(txtcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTelephone1)
                    .addComponent(txttelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmail1)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlinkedin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfax)
                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lbltext, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jCheckBox2.setText("Personal Records");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        createpanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Personal Records");

        lblssn.setText("SSN");

        lblmedrec.setText("Medical Record Number:");

        lblhealthplan.setText("HealthPlanNumber:");

        lblbankacc.setText("BankAccount:");

        lbllicense.setText("License Number:");

        lblvehicle.setText("Vehicle Identifier Number:");

        lbldev.setText("Device Identification Number:");

        lblIntProt.setText("Internet Protocol");

        txtinternetprotocol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinternetprotocolActionPerformed(evt);
            }
        });
        txtinternetprotocol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtinternetprotocolKeyReleased(evt);
            }
        });

        txtssn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtssnKeyReleased(evt);
            }
        });

        txtmedrec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmedrecKeyReleased(evt);
            }
        });

        txthealthplan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthealthplanKeyReleased(evt);
            }
        });

        txtbankacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbankaccKeyReleased(evt);
            }
        });

        txtlicense.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlicenseKeyReleased(evt);
            }
        });

        txtvehicle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtvehicleKeyReleased(evt);
            }
        });

        txtdev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdevKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout createpanel1Layout = new javax.swing.GroupLayout(createpanel1);
        createpanel1.setLayout(createpanel1Layout);
        createpanel1Layout.setHorizontalGroup(
            createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createpanel1Layout.createSequentialGroup()
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createpanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(createpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblssn))
                    .addGroup(createpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblhealthplan))
                    .addGroup(createpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblbankacc)))
                .addGap(62, 166, Short.MAX_VALUE))
            .addGroup(createpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createpanel1Layout.createSequentialGroup()
                        .addComponent(lblIntProt)
                        .addGap(101, 101, 101)
                        .addComponent(txtinternetprotocol))
                    .addGroup(createpanel1Layout.createSequentialGroup()
                        .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldev)
                            .addComponent(lblvehicle))
                        .addGap(18, 18, 18)
                        .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvehicle)
                            .addComponent(txtdev)))
                    .addGroup(createpanel1Layout.createSequentialGroup()
                        .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllicense)
                            .addComponent(lblmedrec))
                        .addGap(53, 53, 53)
                        .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbankacc)
                            .addComponent(txtlicense)
                            .addComponent(txthealthplan)
                            .addComponent(txtmedrec)
                            .addComponent(txtssn))))
                .addContainerGap())
        );
        createpanel1Layout.setVerticalGroup(
            createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblssn))
                .addGap(18, 18, 18)
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmedrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmedrec))
                .addGap(32, 32, 32)
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhealthplan)
                    .addComponent(txthealthplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankacc)
                    .addComponent(txtbankacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbllicense)
                    .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvehicle)
                    .addComponent(txtvehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntProt)
                    .addComponent(txtinternetprotocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        btnphoto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnphoto.setText("Upload Photo");
        btnphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnFax))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnphoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jCheckBox2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(createpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnphoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnFax)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"SUCCESS,Information Saved");
        if(jCheckBox1.isSelected() == true) {
            
            
            product.setDob(jDateChooser1.getDate());
     
            
         } 
            
        
        if(jCheckBox2.isSelected() == true){
  
        product.setIntProt(txtinternetprotocol.getText());
        
        }
       // JOptionPane.showMessageDialog(this,"SUCCESS,Information Saved");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseMoved

    private void txtinternetprotocolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinternetprotocolActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtinternetprotocolActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            
            createpanel.setVisible(true);
        }
        else{
            createpanel.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox2.isSelected())
         {
            createpanel1.setVisible(true);
        }else{
           createpanel1.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void txttelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelephoneActionPerformed

    private void txttelephoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelephoneKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txttelephoneKeyTyped

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,30}";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(txtname.getText());
        if(!match.matches()){
            lbltext.setText("Invalid Name");
        }
        else{
            lbltext.setText(null);
            product.setName(txtname.getText());
        }
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^([\\w-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([\\w-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(txtemail.getText());
        if(!match.matches()){
            lbltext.setText("Invalid Email");
        }
        else{
            lbltext.setText(null);
             product.setEmailAd(txtemail.getText());
        }
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtssnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtssnKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^\\d{3}-?\\d{2}-?\\d{4}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(txtssn.getText());
        if(!match.matches()){
            lbltext.setText("Invalid SSN");
        }
        else{
            lbltext.setText(null);
             product.setSsn(txtssn.getText());
        }
        
    }//GEN-LAST:event_txtssnKeyReleased

    private void btnphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotoActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
       //Specifying  the types of files that can be added by creating filter and specifying the constraints.
       FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg,jpeg,gif,png ", "jpg", "jpeg","gif", "png");
       //Setting the filter to filechooser.
       filechooser.setFileFilter(filter);
       int selectedfile = filechooser.showOpenDialog(null);
       
       //Using an if function to check if the files selected is as per the specified constraints using APPROVE_OPTION
       if(selectedfile == JFileChooser.APPROVE_OPTION){
           //Getting the selected file and storing it in file object.
           File file = filechooser.getSelectedFile();
           //Storing the absolute file name in a string variable SelectedImagePath
           product.setPath(file.getAbsolutePath());    // for setImg_src , create a variable like this in main java class as  string.
           
           //Displaying confirmation message saying "Image Saved". 
           JOptionPane.showMessageDialog(null, "Image Uploaded."); 
        
    }//GEN-LAST:event_btnphotoActionPerformed
    }
    private void txtcountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcountryKeyReleased
        // TODO add your handling code here:
        String MODEL = "^[a-zA-Z]{0,30}$";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txtcountry.getText());
        if(!match.matches()){
            lbltext.setText("Invalid Country");
        }
        else{
            lbltext.setText(null);
            product.setCountry(txtcountry.getText());
        }
        
    }//GEN-LAST:event_txtcountryKeyReleased

    private void txtlinkedin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlinkedin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlinkedin1ActionPerformed

    private void txtlinkedin1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlinkedin1KeyReleased
        // TODO add your handling code here:
        String MODEL = "^https:\\\\/\\\\/[a-z]{2,3}\\\\.linkedin\\\\.com\\\\/.*$";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txtlinkedin1.getText());
        if(!match.matches()){
            lbltext.setText("Invalid LinkedIn Details");
        }
        else{
            lbltext.setText(null);
            product.setLinkedIn(txtlinkedin1.getText());
        }
    }//GEN-LAST:event_txtlinkedin1KeyReleased

    private void txtmedrecKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmedrecKeyReleased
        // TODO add your handling code here:
        String MODEL = "^[1-09]{7}$";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txtmedrec.getText());
        if(!match.matches()){
            lbltext.setText("Invalid LinkedIn Details");
        }
        else{
               lbltext.setText(null);
               product.setMedRec(txtmedrec.getText());
        }
        
    }//GEN-LAST:event_txtmedrecKeyReleased

    private void txthealthplanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthealthplanKeyReleased
        // TODO add your handling code here:
        String MODEL = "^\\b\\d[A-Z]{2}\\d-[A-Z]{2}\\d-[A-Z]{2}\\d{2}\\b $";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txthealthplan.getText());
        if(!match.matches()){
            lbltext.setText("Invalid Health Plan Details");
        }
        else{
            lbltext.setText(null);
            product.setHealthPlan(txthealthplan.getText());
        }
    }//GEN-LAST:event_txthealthplanKeyReleased

    private void txtinternetprotocolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinternetprotocolKeyReleased
        // TODO add your handling code here:
        String MODEL = "^([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})$";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txtinternetprotocol.getText());
        if(!match.matches()){
            lbltext.setText("Invalid IP Details");
        }
        else{
            lbltext.setText(null);
            product.setIntProt(txtinternetprotocol.getText());
        }
    }//GEN-LAST:event_txtinternetprotocolKeyReleased

    private void txtfaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaxKeyReleased
        // TODO add your handling code here:
        String MODEL = "/^\\+?[0-9]{7,}$/";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txtfax.getText());
        if(!match.matches()){
            lbltext.setText("Invalid Fax details");
        }
        else{
            lbltext.setText(null);
            product.setfax(txtfax.getText());
        }
    }//GEN-LAST:event_txtfaxKeyReleased

    private void txtbankaccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbankaccKeyReleased
        // TODO add your handling code here:
        String MODEL = "^[0-9]{10}$";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txtbankacc.getText());
        if(!match.matches()){
            lbltext.setText("Invalid bank Details");
        }
        else{
            lbltext.setText(null);
            product.setBankAcc(txtbankacc.getText());
     
        }
    }//GEN-LAST:event_txtbankaccKeyReleased

    private void txtlicenseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicenseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlicenseKeyReleased

    private void txtvehicleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvehicleKeyReleased
        // TODO add your handling code here:
        String MODEL = "^[A-Z]{1,3}-[A-Z]{1,2}-[0-9]{1,4}$";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txtvehicle.getText());
        if(!match.matches()){
            lbltext.setText("Invalid bank Details");
        }
        else{
            lbltext.setText(null);
            product.setVehIden(txtvehicle.getText());
           
        }
    }//GEN-LAST:event_txtvehicleKeyReleased

    private void txttelephoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelephoneKeyReleased
        // TODO add your handling code here:
        
        String MODEL = "^(\\\\+\\\\d{1,2}\\\\s)?\\\\(?\\\\d{3}\\\\)?[\\\\s.-]\\\\d{3}[\\\\s.-]\\\\d{4}$";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match= mod.matcher(txttelephone.getText());
        if(!match.matches()){
            lbltext.setText("Invalid Telephone");
        }
        else{
            lbltext.setText(null);
            product.setTelNum(txttelephone.getText());
            
        }
    }//GEN-LAST:event_txttelephoneKeyReleased

    private void txtdevKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdevKeyReleased
        // TODO add your handling code here:
        String MODEL ="^([A-F0-9]{40})$";
        Pattern mod = Pattern.compile(MODEL);
        Matcher match = mod.matcher(txtdev.getText());
        if(!match.matches()){
            
            lbltext.setText("Invalid device Identification");
        }
        else{
            lbltext.setText(null);
            product.setDevIden(txtdev.getText());
            
        }
                     
    }//GEN-LAST:event_txtdevKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCountry1;
    private javax.swing.JLabel btnDOB1;
    private javax.swing.JLabel btnEmail1;
    private javax.swing.JLabel btnFax;
    private javax.swing.JLabel btnName1;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel btnTelephone1;
    private javax.swing.JButton btnphoto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel createpanel;
    private javax.swing.JPanel createpanel1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblIntProt;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbankacc;
    private javax.swing.JLabel lbldev;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblhealthplan;
    private javax.swing.JLabel lbllicense;
    private javax.swing.JLabel lblmedrec;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lbltext;
    private javax.swing.JLabel lblvehicle;
    private javax.swing.JTextField txtbankacc;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextField txtdev;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txthealthplan;
    private javax.swing.JTextField txtinternetprotocol;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtlinkedin1;
    private javax.swing.JTextField txtmedrec;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txttelephone;
    private javax.swing.JTextField txtvehicle;
    // End of variables declaration//GEN-END:variables
}